[workspace]
members = ["macros", "runtime/tokio", "runtime/smol", "transport_tcp", "integration_test"]

[package]
name = "occams-rpc"
version = "0.1.0"
edition = "2024"
authors = ["plan <frostyplanet@gmail.com>"]
categories = ["concurrency", "network-programming"]
repository = "https://github.com/NaturalIO/occams-rpc"
documentation = "https://docs.rs/occams-rpc"
keywords = ["networking", "rpc"]
license = "MIT"
description = """
A modular, plugable RPC for high throughput scenario, supports various runtime,
with a low-level streaming interface, and high-level remote API call interface.
"""

[dependencies]
occams-rpc-macros = { path = "macros" }
log = { version = "0.4", features = ["std", "kv_unstable"] }
captains-log = "0.14"
async-trait = "0.1"
futures = "0.3"
zerocopy = "0.2"
io-buffer = "1"
rustc-hash = "1.1"
crossfire = "2.1"
sync-utils = "0"
serde = "1"
rmp-serde = "1.1"
pin-project-lite = "0"

[features]
default = []
#msgp = [dep:rpm-serde]

[dev-dependencies]
serde_derive = "1"
