[package]
name = "occams-rpc"
version = "0.1.0"
edition = "2024"
authors = ["plan <frostyplanet@gmail.com>"]
categories = ["concurrency", "network-programming"]
repository = "https://github.com/NaturalIO/occams-rpc"
documentation = "https://docs.rs/occams-rpc"
keywords = ["networking", "rpc"]
license = "MIT"
description = """
A light-weight customizable logger which have concurrency in mind.
Allow for multi-process/thread/coroutine programing,
and can change log setting on the fly.
"""

[dependencies]
log = { version = "0.4", features = ["std", "kv_unstable"] }
captains-log = "0"
signal-hook = { version = "0" }
nix = "0"

[dev-dependencies]

