[workspace]
members = ["macros", "transport_tcp"]

[package]
name = "occams-rpc"
version = "0.1.0"
edition = "2024"
authors = ["plan <frostyplanet@gmail.com>"]
categories = ["concurrency", "network-programming"]
repository = "https://github.com/NaturalIO/occams-rpc"
documentation = "https://docs.rs/occams-rpc"
keywords = ["networking", "rpc"]
license = "MIT"
description = """
A light-weight customizable logger which have concurrency in mind.
Allow for multi-process/thread/coroutine programing,
and can change log setting on the fly.
"""

[dependencies]
occams-rpc-macros = { path = "macros" }
log = { version = "0.4", features = ["std", "kv_unstable"] }
captains-log = "0.14"
nix = "0"
close_fds = "0.3.2"
tokio = { version = "1", features = ["net", "io-util", "time", "rt"] }
async-io = "2.6"
async-trait = "0.1"
futures = "0.3"
zerocopy = "0.2"
io-buffer = "1"
rustc-hash = "1.1"
crossfire = "2.1"
sync-utils = "0"
serde = "1"
rmp-serde = "1.1"
pin-project-lite = "0"

[features]
default = []
#msgp = [dep:rpm-serde]

[dev-dependencies]
tokio = { version = "1", features = ["net", "io-util", "time", "sync", "rt", "rt-multi-thread"] }
rmp-serde = "1.1"
display_attr = "0.1"
serde_derive = "1"
