use io_buffer::Buffer;
use occams_rpc_core::{
    Codec,
    error::{EncodedErr, RpcErrCodec, RpcError, RpcIntErr},
};
use occams_rpc_stream::server::{RespNoti, RespReceiver};
use rustc_hash::FxHashMap;
use serde::{Deserialize, Serialize};
use std::fmt;
use std::sync::Arc;

pub struct Request<C: Codec> {
    pub seq: u64,
    pub service: String,
    pub method: String,
    pub req: Option<Vec<u8>>,
    pub codec: Arc<C>,
    pub noti: RespNoti<Response>,
}

impl<C: Codec> Request<C> {
    #[inline]
    pub fn decode<'a, R: Deserialize<'a>>(&'a mut self, buf: &'a [u8]) -> Result<R, ()> {
        self.codec.decode::<R>(buf)
    }

    #[inline(always)]
    pub fn set_result<R: Serialize>(self, resp: R) {
        match self.codec.encode::<R>(&resp) {
            Err(()) => {
                self.noti.done(Response {
                    seq: self.seq,
                    msg: None,
                    res: Err(RpcIntErr::Encode.into()),
                });
            }
            Ok(msg) => {
                self.noti.done(Response { seq: self.seq, msg: Some(msg), res: Ok(()) });
            }
        }
    }

    #[inline(always)]
    pub fn set_rpc_error(self, e: RpcIntErr) {
        self.noti.done(Response { seq: self.seq, msg: None, res: Err(e.into()) });
    }

    #[inline(always)]
    pub fn set_error<E: RpcErrCodec>(self, e: RpcError<E>) {
        let encoded_err = match e {
            RpcError::Rpc(rpc_int_err) => rpc_int_err.into(),
            RpcError::User(user_err) => user_err.encode(self.codec.as_ref()),
        };
        self.noti.done(Response { seq: self.seq, msg: None, res: Err(encoded_err) });
    }
}

pub struct Response {
    pub seq: u64,
    pub msg: Option<Vec<u8>>,
    pub res: Result<(), EncodedErr>,
}

impl fmt::Debug for Response {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(f, "resp {} res {:?}", self.seq, self.res)
    }
}

/// RespReceiver for the API interface
pub struct RespReceiverAPI();

impl RespReceiver for RespReceiverAPI {
    type ChannelItem = Response;

    #[inline]
    fn encode_resp<C: Codec>(
        _codec: &C, mut item: Self::ChannelItem,
    ) -> (u64, Result<(Vec<u8>, Option<Buffer>), EncodedErr>) {
        match item.res {
            Ok(()) => {
                let msg = item.msg.take().unwrap();
                (item.seq, Ok((msg, None)))
            }
            Err(e) => (item.seq, Err(e)),
        }
    }
}

/// Service handling code generated by macro
///
/// A ServiceStatic can be:
/// - #[service]: a class with multi method, if only one service, ignore `req.service`.
/// - #[service_mux_struct]: a struct that contains serveral service, each field is a service,
/// match `req.service` by `ServiceTrait::ServiceName` field
pub trait ServiceStatic<C: Codec>: Send + Sync + 'static + Sized {
    /// For server_mux_struct to match
    const SERVICE_NAME: &'static str;

    /// match req.method
    ///     match req.decode::<RequestType>() {
    ///         Err(())=>{
    ///             req.set_error(occams_rpc_core::error::RPC_ERR_DECODE);
    ///             returnl
    ///         }
    ///         Ok(arg)=>{
    ///             match self.#method(arg).await {
    ///                 Ok(resp)=>{
    ///                     req.set_result(resp);
    ///                 }
    ///                 Err(e)=>{
    ///                     req.set_error()
    ///                 }
    ///             }
    ///         }
    ///     }
    fn serve(&self, req: Request<C>) -> impl Future<Output = ()> + Send + Sized;
}

impl<S: ServiceStatic<C>, C: Codec> ServiceStatic<C> for Arc<S> {
    const SERVICE_NAME: &'static str = S::SERVICE_NAME;

    #[inline(always)]
    fn serve(&self, req: Request<C>) -> impl Future<Output = ()> + Send + Sized {
        self.as_ref().serve(req)
    }
}

/// This is the async_trait version of Service trait
///
/// cannot be used by #[service_mux_struct], only used by ServiceMuxDyn
#[async_trait::async_trait]
pub trait ServiceDyn<C: Codec>: Send + Sync + 'static {
    fn get_service_name(&self) -> &'static str;

    async fn serve_dyn(&self, req: Request<C>);
}

#[async_trait::async_trait]
impl<S: ServiceDyn<C> + Sync, C: Codec> ServiceDyn<C> for Arc<S> {
    #[inline(always)]
    fn get_service_name(&self) -> &'static str {
        self.as_ref().get_service_name()
    }

    #[inline(always)]
    async fn serve_dyn(&self, req: Request<C>) {
        self.as_ref().serve_dyn(req).await
    }
}

/// A Service mux dispatch with hashmap
///
/// Only accepts ServiceDyn register, but provide ServiceDyn and ServiceStatic for calling
pub struct ServiceMuxDyn<C: Codec> {
    map: FxHashMap<&'static str, Arc<dyn ServiceDyn<C>>>,
}

impl<C: Codec> ServiceMuxDyn<C> {
    #[inline]
    pub fn new() -> Self {
        Self { map: Default::default() }
    }

    #[inline]
    pub fn add(&mut self, service: Arc<dyn ServiceDyn<C>>) {
        self.map.insert(service.get_service_name(), service);
    }
}

impl<C: Codec> ServiceStatic<C> for ServiceMuxDyn<C> {
    const SERVICE_NAME: &'static str = "";

    #[inline(always)]
    fn serve(&self, req: Request<C>) -> impl Future<Output = ()> + Send + Sized {
        async move {
            if let Some(service) = self.map.get(req.service.as_str()) {
                service.serve_dyn(req).await
            } else {
                req.set_rpc_error(RpcIntErr::Service);
            }
        }
    }
}

#[async_trait::async_trait]
impl<C: Codec> ServiceDyn<C> for ServiceMuxDyn<C> {
    fn get_service_name(&self) -> &'static str {
        unreachable!();
    }

    #[inline(always)]
    async fn serve_dyn(&self, req: Request<C>) {
        self.serve(req).await
    }
}

/*
pub struct ApiReqDispatch<C: Codec> {
    codec: C,
    service_dispatch:
}


impl<C: Codec> ReqDispatch<RespReceiverAPI> for D {

    async fn dispatch_req<'a>(
        &'a self, req: RpcSvrReq<'a>, noti: RespNoti<Response>,
    ) -> Result<(), ()> {
        if let RpcAction::Str(action) = req.action {
            if let Some(service, method) = action.split_once('.') {

            }
        }
        warn!("{:?} invalid action", req);
        return Err(())
    }
}

pub trait ServiceDisptach {

    fn dispatch(&self, req: Request<C>) -> impl Future<Output=()> + Send;
}
*/
