name: smol-x86
permissions:
  contents: read
  pull-requests: write
on:
  schedule: [cron: "10 */5 * * *"]
  pull_request:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: test all
      run: make all-test -- "-F smol"

    - name: test release
      run: make test-basic -- "-F smol --release"

    - name: test pressure releaes
      run: make test-pressure -- "-F smol"
